
# Code generated by ChatGBT.

def goldbach(n):
    primes = []
    for num in range(2, n+1):
        if all(num%i!=0 for i in range(2,num)):
            primes.append(num)
            print(num)
    for i in range(4, n+1, 2):
        found = False
        for prime in primes:
            if prime > i:
                break
            if (i - prime) in primes:
                found = True
                break
        if not found:
            return i
    return None

n = int(input("Enter a number: "))
result = goldbach(n)
if result:
    print("The first number that breaks the Goldbach's Conjecture is:", result)
else:
    print("No number found that breaks the Goldbach's Conjecture up to", n)